FROM python:3.4

COPY ./lib/python3.4/site-packages /usr/local/lib/python3.4/site-packages

WORKDIR /usr/src/app
COPY tensorflow_apps ./

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]